use_frameworks!

platform :ios, '11.0'

target 'Viewtiful_Example' do
  pod 'SnapKit', '~> 5.0.0'
  pod 'AddThen', '~> 0.1.3'
#  pod 'RxSwift', '~> 5'
  pod 'Viewtiful', :path => '../'

  target 'Viewtiful_Tests' do
    inherit! :search_paths
    
  end
end
